# This workflow will release and publish the project with Maven
# It uses Maven release to release the process including deploy.
# Deployment is done to GitHub Package registry.

name: Maven Release

on:
  push:
  pull_request:

jobs:
  release:
    name: Maven Release

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGES_DEPLOY_TOKEN }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[
        { "id": "github-zetool-common", "name": "GitHub zetool Apache Maven Packages", "url": "https://maven.pkg.github.com/zetool/common" },
        { "id": "github-zetool-components", "name": "GitHub zetool Apache Maven Packages", "url": "https://maven.pkg.github.com/zetool/components" },
        { "id": "tweety", "name": "TweetyProject", "url": "https://tweetyproject.org/mvn" },
        { "id": "ekito-public-releases", "name": "Ekito", "url": "https://raw.github.com/Ekito/maven-repo/master/releases" }
        ]'
        servers: '[{ "id": "github", "username": "zetool-bot", "password": "${GITHUB_TOKEN}" }]'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
